#!/usr/bin/env bash
#
# ░░░░░█▀▀░█░█░█▀▀░▀█▀░█▀█░█▄█░░░█▀▀░█░█░█▀▀░█░░░█░░░░░░ #
# ░░░░░█░░░█░█░▀▀█░░█░░█░█░█░█░░░▀▀█░█▀█░█▀▀░█░░░█░░░░░░ #
# ░░░░░▀▀▀░▀▀▀░▀▀▀░░▀░░▀▀▀░▀░▀░░░▀▀▀░▀░▀░▀▀▀░▀▀▀░▀▀▀░░░░ #
#
# Small functions to set up GNOME Shell quickly.

source ./helpers/gnome

set_keybindings() {

  _set_sane_defaults

  _disable_ibus_emoji

  _set_wm_keybindings

  _set_shell_keybindings
}

get_keybindings() {
  local show_all=false

  printf "Select schema(s):\n"
  select schema in "${schemas[@]}"; do
    case ${schema} in
    all) show_all=true ;;
    *) _show_schema "${schema}" ;;
    esac
    break
  done

  if [[ ${show_all} == true ]]; then
    for schema in "${schemas[@]}"; do
      if [[ "${schema}" != "all" ]]; then
        _show_schema "${schema}"
      fi
    done
  fi
}

delete_keybindings() {
  local key_count=0
  local modified=0

  for schema in "${schemas[@]}"; do
    printf "==> \x1b[34m%s\x1b[0m\n" ${schema}

    local keys=($(gsettings list-keys "${schema}"))

    for key in "${keys[@]}"; do
      ((key_count++))
      local kind="$(gsettings range ${schema} ${key})"
      if [[ "${kind}" == *array* || "${kind}" == *as* ]]; then
        ((modified++))
        gsettings set "${schema}" "${key}" "[]"
        printf "Key \x1b[34m%s\x1b[0m disabled.\n" "${key}"
      else
        printf "\x1b[31mnoop\n\x1b[0m"
      fi
    done
  done

  printf "Done! %d of %d keybindings disabled.\n" "${modified}" "${key_count}"
}
